http://localhost:3003/api/blogs
###
http://localhost:3003/api/blogs/633be68d35e64c3bb5d76826
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpZCI6IjYzM2VjZWIyZmZjYWMxNDQzOGMxYmNkYiIsImlhdCI6MTY2NTA2MTI4NCwiZXhwIjoxNjY2MzU3Mjg0fQ.P2BXH1hRES7B-Mwg5hZg18RfoHPku_d1MUio7TN5_Uc

{
    "title": "test title",
    "author": "John Doe",
    "url": "http://somesite.com",
    "likes": 0
}
###
DELETE http://localhost:3003/api/blogs/633ed25fffcac14438c1bd1d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpZCI6IjYzM2VjZWIyZmZjYWMxNDQzOGMxYmNkYiIsImlhdCI6MTY2NTA2MTI4NCwiZXhwIjoxNjY2MzU3Mjg0fQ.P2BXH1hRES7B-Mwg5hZg18RfoHPku_d1MUio7TN5_Uc

###
PUT http://localhost:3003/api/blogs/633be68d35e64c3bb5d76826/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4xMiIsImlkIjoiNjMzMmE1ZDdhN2I5YmYxMDRiYzY5MjlkIiwiaWF0IjoxNjY0NTI4MTg4LCJleHAiOjE2NjU4MjQxODh9.fB1josPK5k1mAcVAQS0ImwGW2h6yXIPr33HZhRFDFNQ
